name: venera
description: "A comic app."
publish_to: 'none'

version: 1.1.2+112

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: 3.27.1

dependencies:
  flutter:
    sdk: flutter
  path_provider: any
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  window_manager: ^0.4.3
  sqlite3: ^2.4.7
  sqlite3_flutter_libs: any
  flutter_qjs:
    git:
      url: https://github.com/wgh136/flutter_qjs
      ref: 1657f62fe7545ac43a339e0a5ee2b82bacd81e9f
  crypto: ^3.0.6
  dio: ^5.7.0
  html: ^0.15.5
  pointycastle: any
  url_launcher: ^6.3.0
  path: ^1.9.0
  photo_view:
    git:
      url: https://github.com/wgh136/photo_view
      ref: 94724a0b
  mime: ^2.0.0
  share_plus: ^10.0.2
  scrollable_positioned_list:
    git:
      url: https://github.com/venera-app/flutter.widgets
      ref: 09e756b1f1b04e6298318d99ec20a787fb360f59
      path: packages/scrollable_positioned_list
  flutter_reorderable_grid_view: ^5.4.0
  yaml: any
  uuid: ^4.5.1
  desktop_webview_window:
    git:
      url: https://github.com/wgh136/flutter_desktop_webview
      path: packages/desktop_webview_window
  flutter_inappwebview: ^6.1.5
  app_links: ^6.3.2
  sliver_tools: ^0.2.12
  flutter_file_dialog: ^3.0.2
  file_selector: ^1.0.3
  zip_flutter: ^0.0.5
  lodepng_flutter:
    git:
      url: https://github.com/venera-app/lodepng_flutter
      ref: 9a784b193af5d55b2a35e58fa390bda3e4f35d00
  rhttp: 0.9.6
  webdav_client:
    git:
      url: https://github.com/wgh136/webdav_client
      ref: 285f87f15bccd2d5d5ff443761348c6ee47b98d1
  battery_plus: ^6.2.0
  local_auth: ^2.3.0
  flutter_saf:
    git: 
      url: https://github.com/pkuislm/flutter_saf.git
      ref: 7637b8b67d0a831f3cd7e702b8173e300880d32e
  pdf: ^3.11.1
  dynamic_color: ^1.7.0
  shimmer: ^3.0.0
  flutter_memory_info: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_to_arch: ^1.0.0
  flutter_to_debian:

flutter:
  uses-material-design: true
  assets:
    - assets/translation.json
    - assets/init.js
    - assets/app_icon.png
    - assets/tags.json
    - assets/tags_tw.json

flutter_to_arch:
  name: Venera
  icon: debian/gui/venera.png
  categories: Utility
  keywords: Flutter;comic;images;
  url: https://github.com/venera-app/venera
  depends:
    - gtk3
    - webkit2gtk-4.1
